---
- name: Install Nautobot
  hosts: [nautobot]
  gather_facts: true
  become: yes
  vars:
    nautobot__remove_existing_container: false
    nautobot__superuser_name: admin
    nautobot__superuser_password: admin
    nautobot__superuser_api_token: "1234567890abcdefghijklmnopqrstuvwxyz0987"
    nautobot__napalm_username: cisco
    nautobot__napalm_password: cisco
    nautobot__ldap_auth_server_ip: 192.168.71.10
    nautobot__ldap_auth_server_port: 3890
    nautobot__ldap_search_users: "ou=people,dc=example,dc=com"
    nautobot__ldap_search_groups: "ou=groups,dc=example,dc=com"
    nautobot__ldap_auth_bind_dn: "CN=readonly,OU=people,DC=example,DC=com"
    nautobot__ldap_auth_bind_pass: "readonly"
    nautobot__plugins:
      - plugin_name: nautobot_device_onboarding
        plugin_config: {
              "nautobot_device_onboarding": {
                "default_ip_status": "Active",
                "default_device_role": "onboarding",
                "skip_device_type_on_update": True,
              }
            }
      - plugin_name: nautobot-ssot
        plugin_config: {}
      - plugin_name: nautobot-plugin-nornir
        plugin_config: {
          "nautobot_plugin_nornir": {
            "use_config_context": {"secrets": False, "connection_options": True},
            # Optionally set global connection options.
            "connection_options": {
                "napalm": {
                    "extras": {
                        "optional_args": {"global_delay_factor": 1},
                    },
                },
                "netmiko": {
                    "extras": {
                        "global_delay_factor": 1,
                    },
                },
            },
            "nornir_settings": {
                "credentials": "nautobot_plugin_nornir.plugins.credentials.env_vars.CredentialsEnvVars",
                "runner": {
                    "plugin": "threaded",
                    "options": {
                        "num_workers": 20,
                    },
                },
            },
          }
        }
      - plugin_name: nautobot-golden-config
        plugin_config: {
            "nautobot_golden_config": {
              "per_feature_bar_width": 0.15,
              "per_feature_width": 13,
              "per_feature_height": 4,
              "enable_backup": False,
              "enable_compliance": False,
              "enable_intended": True,
              "enable_sotagg": True,
              "sot_agg_transposer": None,
              "enable_postprocessing": False,
              "postprocessing_callables": [],
              "postprocessing_subscribed": [],
              "platform_slug_map": None,
              # "get_custom_compliance": "my.custom_compliance.func"
            }
        }
  tasks:
    # - name: Check if nautobot is installed
    #   include_role:
    #     name: docker
    - name: Check if nautobot is installed
      include_role:
        name: docker_nautobot
