---
- name: restart nautobot
  docker_container:
    name: "{{ nautobot__name }}"
    restart: true
- name: restart nautobot-stack
  docker_container:
    name: "{{ nautobot__name }}"
    restart: true
- name: restart nautobot-stack
  docker_container:
    name: "{{ nautobot__name }}-worker"
    restart: true
- name: restart nautobot-stack
  docker_container:
    name: "{{ nautobot__name }}-celery-worker"
    restart: true
- name: restart nautobot-stack
  docker_container:
    name: "{{ nautobot__name }}-celery-beat"
    restart: true
- name: restart nautobot-stack
  docker_container:
    name: "{{ nautobot__name }}-redis"
    restart: true
- name: restart nautobot-stack
  docker_container:
    name: "{{ nautobot__name }}-db"
    restart: true
