---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-errors: true
    ignore-certs: true
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "bsmeding/ansible_cicd_${MOLECULE_DISTRO:-debian12}:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    verify: ${MOLECULE_PLAYBOOK_VERIFY:-verify.yml}
