---
- name: Prepare Nautobot host paths
  hosts: localhost
  gather_facts: false
  vars:
    molecule_nautobot_home: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') | default('/tmp/molecule', true) }}/nautobot"
    molecule_nautobot_directories:
      - config
      - config/custom_jinja_filters
  tasks:
    - name: Ensure Nautobot host directories exist and are writable
      ansible.builtin.file:
        path: "{{ molecule_nautobot_home }}/{{ item }}"
        state: directory
        mode: "0777"
      loop: "{{ molecule_nautobot_directories }}"

    - name: Touch Nautobot config file on host
      ansible.builtin.file:
        path: "{{ molecule_nautobot_home }}/config/nautobot_config.py"
        state: touch
        mode: "0666"

    - name: Touch Nautobot custom filters file on host
      ansible.builtin.file:
        path: "{{ molecule_nautobot_home }}/config/custom_jinja_filters/ipaddress_filters.py"
        state: touch
        mode: "0666"
