---
- name: Verify Nautobot Docker role
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Verify Nautobot container is running
      community.docker.docker_container_info:
        name: "{{ nautobot__name }}"
      register: nautobot_container_info

    - name: Assert Nautobot container status
      ansible.builtin.assert:
        that:
          - nautobot_container_info.exists
          - nautobot_container_info.container.State.Running | default(false)
        fail_msg: "Nautobot container is not running"

    - name: Check HTTP endpoint responds
      ansible.builtin.uri:
        url: "http://localhost:{{ nautobot__port_http }}"
        status_code: 200
      register: nautobot_http
      retries: 5
      delay: 2
      until: nautobot_http.status == 200
      changed_when: false
