---
- name: Verify Nautobot Docker role
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Wait for Nautobot HTTP port
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: "{{ nautobot__port_http }}"
        delay: 10
        timeout: 300
      changed_when: false

    - name: Verify Nautobot container is running
      community.docker.docker_container_info:
        name: "{{ nautobot__name }}"
      register: nautobot_container_info

    - name: Assert Nautobot container status
      ansible.builtin.assert:
        that:
          - nautobot_container_info.exists
          - nautobot_container_info.container.State.Running | default(false)
        fail_msg: "Nautobot container is not running"

    - name: Check HTTP endpoint responds
      ansible.builtin.uri:
        url: "http://localhost:{{ nautobot__port_http }}"
        status_code: 200
      register: nautobot_http
      retries: 36
      delay: 5
      until: nautobot_http.status == 200
      changed_when: false
