---
- name: Verify Nautobot Docker role
  hosts: all
  become: true
  gather_facts: false
  vars:
    molecule_nautobot_home: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') | default('/tmp/molecule', true) }}/nautobot"
    molecule_nautobot_http_port: 18080
    molecule_nautobot_https_port: 18443
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Set molecule testing ports
      ansible.builtin.set_fact:
        nautobot__home: "{{ molecule_nautobot_home }}"
        nautobot__port_http: "{{ molecule_nautobot_http_port }}"
        nautobot__port_https: "{{ molecule_nautobot_https_port }}"

    - name: Capture default Nautobot volume mappings
      ansible.builtin.set_fact:
        molecule_default_directory_volumes: "{{ nautobot__directory_volumes }}"
        molecule_default_file_volumes: "{{ nautobot__file_volumes }}"

    - name: Override Nautobot volumes for Molecule workspace
      ansible.builtin.set_fact:
        nautobot__directory_volumes: >
          {{
            [ nautobot__home ~ '/config:/opt/nautobot/config' ]
            + molecule_default_directory_volumes
          }}
        nautobot__file_volumes: []

    - name: Wait for Nautobot HTTP endpoint inside container
      ansible.builtin.command: >
        docker exec {{ nautobot__name }} curl -fsS -o /dev/null http://127.0.0.1:8080
      register: nautobot_http_ready
      retries: 60
      delay: 5
      until: nautobot_http_ready.rc == 0
      changed_when: false

    - name: Verify Nautobot container is running
      community.docker.docker_container_info:
        name: "{{ nautobot__name }}"
      register: nautobot_container_info

    - name: Assert Nautobot container status
      ansible.builtin.assert:
        that:
          - nautobot_container_info.exists
          - nautobot_container_info.container.State.Running | default(false)
        fail_msg: "Nautobot container is not running"

    - name: Check HTTP endpoint responds from inside container
      ansible.builtin.command: >
        docker exec {{ nautobot__name }} curl -fsS -o /dev/null http://127.0.0.1:8080
      register: nautobot_http
      retries: 36
      delay: 5
      until: nautobot_http.rc == 0
      changed_when: false
