---
- name: Verify - Nautobot is running
  hosts: all
  become: false
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - "yml"

    - name: Waits for database migrations (can take up to 5 minutes)
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 8080
        timeout: 300
        delay: 10

    - name: Check if Nautobot login page is running
      ansible.builtin.uri:
        url: "http://127.0.0.1:8080/login/"
        return_content: true
        status_code: 200
      register: local_webserver_output
      until: local_webserver_output.status == 200
      retries: 10
      delay: 10

    - name: Debug content
      ansible.builtin.debug:
        msg: "{{ local_webserver_output.content | truncate(500) }}"
