ARG PYTHON_VER={{ nautobot__image_python_version | default('3.9') }}
ARG NAUTOBOT_IMAGE={{ nautobot__image }}
FROM networktocode/${NAUTOBOT_IMAGE}-py${PYTHON_VER}

RUN pip3 install --upgrade pip wheel 
RUN pip3 install --upgrade nautobot[napalm]

{% if nautobot__plugins is defined %}
{% for plugin in nautobot__plugins %}
RUN pip3 install --no-warn-script-location {{ plugin.plugin_name }}
{% endfor %}
{% endif %}
