ARG PYTHON_VER={{ nautobot__image_python_version | default('3.9') }}
ARG NAUTOBOT_IMAGE={{ nautobot__image }}
# ---------------------------------
# Stage: PreRequistics
# ---------------------------------
# If the Nautobot image tag already contains a "-py" suffix (e.g. "nautobot:stable-py3.12"),
# use it as-is. Otherwise append "-py<version>" to the tag.
{% set _parts = (nautobot__image | string).split(':') %}
{% set _name = _parts[0] %}
{% set _tag = _parts[1] if _parts|length > 1 else 'latest' %}
FROM {% if '-py' in _tag %}networktocode/{{ _name }}:{{ _tag }}{% else %}networktocode/{{ _name }}:{{ _tag }}-py{{ nautobot__image_python_version | default('3.9') }}{% endif %} as base
USER 0

{% if http_proxy is defined and http_proxy != '' %}
ENV http_proxy {{ http_proxy }}
{% endif %}
{% if https_proxy is defined and https_proxy != '' %}
ENV https_proxy {{ https_proxy }}
{% endif %}
{% if no_proxy is defined and no_proxy != '' %}
ENV no_proxy {{ no_proxy }}
{% endif %}

RUN apt-get update -y && apt-get install -y libldap2-dev libsasl2-dev libssl-dev

# Root install SAML dependencies # Removed llibxmlsec1-dev 17-09-23
RUN apt-get update -y && apt-get install -y libxmlsec1-openssl pkg-config 

# Install network tools used by Jobs
RUN apt-get update -y && apt-get install -y net-tools iputils-ping  dnsutils

# ---------------------------------
# Stage: Builder
# ---------------------------------
FROM base as builder

RUN apt-get install -y gcc && \
    apt-get autoremove -y && \
    apt-get clean all && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip wheel {{ nautobot__pip_install_extra_args }}
RUN pip3 install --upgrade setuptools {{ nautobot__pip_install_extra_args }}
{% set image_tag = (nautobot__image | string).split(':')[1:] | first | default('') %}
{% set tag_parts = image_tag.split('-') %}
{% set version_part = tag_parts[0] %}
{% if version_part | regex_search('^[0-9]+\\.[0-9]+\\.[0-9]+') %}
RUN pip3 install --upgrade nautobot[ldap]=={{ version_part }} {{ nautobot__pip_install_extra_args }}
{% else %}
RUN pip3 install --upgrade nautobot[ldap] {{ nautobot__pip_install_extra_args }}
{% endif %}
RUN pip3 install --upgrade ansible-core=={{ nautobot_install_ansible_version | default('2.15.10') }}  {{ nautobot__pip_install_extra_args }}

# Check extra pip packages to install
{% if nautobot__extra_pip_packages is defined %}
{% for pip_package in nautobot__extra_pip_packages %}
RUN pip3 install --upgrade {{ pip_package }} {{ nautobot__pip_install_extra_args }}

{% endfor %}
{% endif %}

# Check Ansible collections
{% if nautobot__install_ansible_collections is defined %}
{% for ansible_collection in nautobot__install_ansible_collections %}
RUN ansible-galaxy collection install {{ ansible_collection }}{% if nautobot__ansible_collection_use_old_galaxy %} --server="https://old-galaxy.ansible.com"{% endif %} --force --ignore-certs

{% endfor %}
{% endif %}

# Check Nautobot plugins
{% if nautobot__plugins is defined %}
RUN pip3 install --upgrade nornir-nautobot {{ nautobot__pip_install_extra_args }}
{% for plugin in nautobot__plugins %}
{% set _plugin_name = plugin.get('plugin_name') %}
{% set _plugin_version = plugin.get('plugin_version') %}
{% set _plugin_pip_extras = plugin.get('plugin_pip_extras') %}
RUN pip3 install --no-warn-script-location {{ _plugin_name }}{% if _plugin_pip_extras is defined %}{{ _plugin_pip_extras }}{% endif %}{% if _plugin_version is defined and _plugin_version %}=={{ _plugin_version }}{% endif %} {{ nautobot__pip_install_extra_args }}

{% endfor %}
{% endif %}


# ---------------------------------
# Stage: Final
# ---------------------------------
FROM base as final
ARG PYTHON_VER
USER 0

COPY --from=builder /usr/local/lib/python${PYTHON_VER}/site-packages /usr/local/lib/python${PYTHON_VER}/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin
USER nautobot

WORKDIR /opt/nautobot